# SUITABLE FOR DEVELOPMENT ONLY!!

services:
  web:
    build: .
    ports:
      - "8000:8000"
    entrypoint:
      - sh
      - scripts/entrypoint_prod.sh
    links:
      - db
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      POSTGRES_HOST: db
      DJANGO_SECRET: anything
      # DJANGO_DEBUG: "true"
      DJANGO_SETTINGS_MODULE: django_.settings
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

